# Site settings
title: Ben van Werkhoven
email: b.van.werkhoven@liacs.leidenuniv.nl
description: > # this means to ignore newlines until "baseurl:"
  Ben van Werkhoven, research software engineer, computer scientist, data scientist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: benvanwerkhoven

# Build settings
markdown: kramdown


collections:
- projects
- personal
- contacts
- publications
